name: Update version number
on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'The new version'
        required: true
jobs:

  Update:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: n1hility/cancel-previous-runs@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Update version number
      run: |
        Scripts/increment_version.sh ${{ github.event.inputs.newVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        branch: update-version-github-action
        commit-message: "chore: updated version"
        title: Update version
        body: Update version.
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}
